---
  - name: add nginx ppa
    sudo: yes
    apt_repository: repo='ppa:nginx/stable'

  - name: update apt-get
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: install packages
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - nginx
      - openssl

  - name: ensure dpharm folder
    sudo: yes
    file: path={{ dpharm_path | dirname }} state=directory

  - name: ensure dpharm certificate
    sudo: yes
    shell: test -e {{ dpharm_path }} || openssl dhparam -out {{ dpharm_path }} 2048

  - name: copy nginx.conf
    sudo: yes
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
    tags:
      - nginx

  - name: setup nginx host file dirs
    sudo: yes
    file: name=/etc/nginx/{{ item }} state=directory owner=root group=root
    with_items:
      - sites-available
      - sites-enabled

  - name: ensure default nginx has been deleted
    sudo: yes
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: Copy nginx default virtual host file
    sudo: yes
    template: src="{{ inventory_dir }}/templates/nginx.default.j2"
              dest="/etc/nginx/sites-available/{{app_name}}"
              owner=root
              group=root

  - name: Link nginx virtual host file
    sudo: yes
    file: src="/etc/nginx/sites-available/{{app_name}}"
          dest="/etc/nginx/sites-enabled/{{app_name}}"
          state=link

  - name: restart nginx
    sudo: yes
    service: name=nginx state=restarted enabled=yes
    tags:
      - nginx
