---
- name: Deploy Web
  hosts: web-server
  gather_facts: false
  vars_files:
    - ["vars/web.yml"]
  roles:
    - common
    - nodejs
    - nginx
    - letsencrypt
  tasks:
    - include: deploy-sources.yml

    - name: Delete existing backend service
      sudo: yes
      ignore_errors: yes
      args:
        chdir: "{{ deploy_app_dir }}"
      shell: forever-service delete {{ app_name }}

    - name: Register backend service
      sudo: yes
      args:
        chdir: "{{ deploy_app_dir }}"
      shell: forever-service install {{ app_name }} --script server.js

    - name: Start backend service
      sudo: yes
      shell: service {{ app_name }} start

    - name: Delete cache
      file: path={{ nginx_cache_dir }} state=absent

    - name: Restart nginx
      sudo: yes
      service: name=nginx state=restarted
