---
  - name: add node ppa
    sudo: yes
    shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

  - name: update apt packages
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: install packages
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - g++
      - make
      - build-essential

  - name: install node and npm
    sudo: yes
    shell: apt-get install -y nodejs

  - name: Install global npm packages
    npm: name={{ item }} global=yes
    sudo: yes
    with_items:
      - forever
      - npm
