---
  - name: ensure python installed
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python)"

  - name: update apt packages
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

  - name: disallow password authentication
    sudo: yes
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present

  - name: restart sshd
    sudo: yes
    service:
      name: sshd
      state: restarted

  - name: install basic apt packages
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - curl
      - node-rimraf
      - unzip
