---
  - name: add certbot repository
    apt_repository: repo={{ item }}
    with_items:
      - "ppa:certbot/certbot"

  - name: update package lists
    apt: update_cache=yes cache_valid_time=3600

  - name: install letsencrypt required packages
    apt: name={{ item }} state=present
    with_items:
      - "certbot"

  - name: ensure root directory is present
    file:
      path: "{{ letsencrypt_root }}"
      state: directory
      mode: 0755

  - name: Restart nginx
    sudo: yes
    service: name=nginx state=restarted

  - name: use letsencrypt webroot plugin
    command: certbot certonly -a webroot --webroot-path={{ letsencrypt_root }} -d {{server_name}} -d www.{{server_name}} --non-interactive --agree-tos --email {{ contact_email }}

  - name: create CRON task for auto-renew
    cron: name="certbot-daily-renew" minute=30 hour=3 job="/usr/bin/certbot renew --quiet --renew-hook \"/bin/systemctl reload nginx\"" state=present

  - name: Copy tls nginx virtual host file
    sudo: yes
    template: src="{{ inventory_dir }}/templates/nginx.j2"
              dest="/etc/nginx/sites-available/{{app_name}}"
              owner=root
              group=root

  - name: Restart nginx
    sudo: yes
    service: name=nginx state=restarted
